/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StProgress {
    /**
    * The visual color style of the progress
    */
    'color': string;
  }
  interface StProgressAttributes extends StencilHTMLAttributes {
    /**
    * The visual color style of the progress
    */
    'color'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StProgress': Components.StProgress;
  }

  interface StencilIntrinsicElements {
    'st-progress': Components.StProgressAttributes;
  }


  interface HTMLStProgressElement extends Components.StProgress, HTMLStencilElement {}
  var HTMLStProgressElement: {
    prototype: HTMLStProgressElement;
    new (): HTMLStProgressElement;
  };

  interface HTMLElementTagNameMap {
    'st-progress': HTMLStProgressElement
  }

  interface ElementTagNameMap {
    'st-progress': HTMLStProgressElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
