/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StAlert {
    /**
    * The class list
    */
    'classnames': string;
  }
  interface StAlertAttributes extends StencilHTMLAttributes {
    /**
    * The class list
    */
    'classnames'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StAlert': Components.StAlert;
  }

  interface StencilIntrinsicElements {
    'st-alert': Components.StAlertAttributes;
  }


  interface HTMLStAlertElement extends Components.StAlert, HTMLStencilElement {}
  var HTMLStAlertElement: {
    prototype: HTMLStAlertElement;
    new (): HTMLStAlertElement;
  };

  interface HTMLElementTagNameMap {
    'st-alert': HTMLStAlertElement
  }

  interface ElementTagNameMap {
    'st-alert': HTMLStAlertElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
